{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.celery.replicas }}
  strategy:
    # kills all old Pods first
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery
      annotations:
        # restart on upgrade
        rollme: {{ randAlphaNum 5 | quote }}
    {{- with .Values.celery.annotations }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote}}
      {{- end }}
    {{- end }}
    spec:
      {{- with .Values.celery.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # celery beat
        - name: celery-beat
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          command: ["/start-beat"]
          volumeMounts:
            - name: wger-celery-beat
              mountPath: /home/wger/beat
              readOnly: false
          {{- if .Values.celery.resources }}
          resources:
            {{- with .Values.celery.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        # celery flower
        {{- if .Values.celery.flower.enabled }}
        - name: celery-flower
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          command: ["/start-flower"]
          {{- if .Values.celery.flower.resources }}
          resources:
            {{- with .Values.celery.flower.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: flower
              containerPort: 5555
              protocol: TCP
        # {{/*- if .Values.celery.flower.enabled */}}
        {{- end }}
      initContainers:
        - name: init-container
          image: docker.io/busybox:latest
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          command:
          {{- include "initContainer.app.command" . | indent 10 }}
      volumes:
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default "wger-celery-beat" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  {{- with .Values.celery.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote}}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.celery.replicasWorker }}
  strategy:
    # kills all old Pods first
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
      annotations:
        # restart on upgrade
        rollme: {{ randAlphaNum 5 | quote }}
    {{- with .Values.celery.annotations }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote}}
      {{- end }}
    {{- end }}
    spec:
      {{- with .Values.celery.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # celery worker
        - name: celery-worker
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          command: ["/start-worker"]
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - celery -A wger inspect ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media
              readOnly: false
          {{- if .Values.celery.resources }}
          resources:
            {{- with .Values.celery.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      initContainers:
      - name: init-container
        image: docker.io/busybox:latest
        imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
        command:
        {{- include "initContainer.app.command" . | indent 10 }}
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.media | default "wger-media" | quote }}
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default "wger-celery-beat" | quote }}
# {{/*- if .Values.celery.enabled */}}
{{- end }}
