apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.celery.flower.secret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  password: {{ include "wger.secretValue" (dict "ctx" $ "name" .Values.celery.flower.secret.name "key" "password" "value" .Values.celery.flower.secret.password "length" 50) | quote }}
