apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.django.secret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  secret-key: {{ include "wger.secretValue" (dict "ctx" $ "name" .Values.app.django.secret.name "key" "secret-key" "value" .Values.app.django.secret.key "length" 50) | quote }}
