---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.django.secret.name | default "django" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  {{ if .Values.app.django.secret.key }}
  secret-key: {{ .Values.app.django.secret.key | quote }}
  {{ else }}
  secret-key: {{ randAlphaNum 50 | quote }}
  {{ end }}
