# updates or creates the secret
{{- define "manipulate" -}}
{{- if (lookup "v1" "Secret" .Release.Namespace .Values.app.mail.secret.name) -}}
  {{- if .Values.app.mail.secret.update -}}
    {{- if .Values.app.mail.secret.password -}}
doit
    {{- end -}}
  {{- end -}}
{{- else -}}
  {{- if .Values.app.mail.secret.password -}}
doit
  {{- end -}}
{{- end -}}
{{- end -}}

{{- if .Values.app.mail.enabled }}
{{- $manipulate := (include "manipulate" .) }}
{{- if eq $manipulate "doit" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.mail.secret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
data:
  {{ .Values.app.mail.secret.key }}: {{ .Values.app.mail.secret.password | b64enc | quote }}
{{- end }}
{{- end }}
